#!/bin/sh
raspi-gpio set 4 op
case "$1" in
  0|off ) raspi-gpio set 4 dl ;;
  1|on  ) raspi-gpio set 4 dh ;;
  *     ) state=$(raspi-gpio get 4 | sed -e 's/.*level=\([01]\).*/\1/'); echo target power: $state    ;;
esac
